services:
  postgres:
    image: postgres:15
    container_name: postgres_bicycle_shop
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: bicycle_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./bicycle-shop-backend/Dockerfile
    container_name: bicycle_shop_backend
    restart: always
    env_file:
      - ./bicycle-shop-backend/.env
    ports:
      - "3030:3030"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./bicycle-shop-frontend
      dockerfile: Dockerfile
    container_name: bicycle_shop_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
