services:
  postgres:
    image: postgres:15
    container_name: postgres_bicycle_shop
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: bicycle_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bicycle_shop_network

  backend:
    build:
      context: .
      dockerfile: ./bicycle-shop-backend/Dockerfile
    container_name: bicycle_shop_backend
    restart: always
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    environment:
      PORT: 3030
      DB_TYPE: postgres
      DB_HOST: postgres_bicycle_shop
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgrespassword
      DB_NAME: bicycle_shop
    networks:
      - bicycle_shop_network

  frontend:
    build:
      context: ./bicycle-shop-frontend
      dockerfile: Dockerfile
    container_name: bicycle_shop_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://bicycle_shop_backend:3030
    networks:
      - bicycle_shop_network

volumes:
  postgres_data:

networks:
  bicycle_shop_network:
    driver: bridge
