FROM node:18-alpine

WORKDIR /app

COPY ./bicycle-shop-backend/package*.json ./bicycle-shop-backend/

WORKDIR /app/bicycle-shop-backend
RUN npm install

COPY ./bicycle-shop-backend ./

EXPOSE 3030

CMD ["sh", "-c", "if [ \"$RUN_SEED\" = \"true\" ]; then npm run seed; fi && npm start"]
