# Usar una imagen base de Node.js
FROM node:18-alpine AS builder

# Establecer directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json al contenedor
COPY package*.json ./

# Instalar dependencias
RUN npm install --legacy-peer-deps

# Copiar el resto del código fuente al contenedor
COPY . .

# Construir la aplicación Next.js
RUN npm run build

# Producción: usar una imagen más ligera
FROM node:18-alpine AS runner

WORKDIR /app

# Copiar el build y dependencias necesarias desde el builder
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/public ./public

# Instalar dependencias de producción
RUN npm install

# Exponer el puerto que usa Next.js
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "start"]
