# Usar una imagen base de Node.js
FROM node:18-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de configuración de npm
COPY package*.json ./

# Instalar todas las dependencias (incluyendo devDependencies)
RUN npm install --legacy-peer-deps

# Copiar el resto del código fuente al contenedor
COPY . .

# Exponer el puerto que usa Next.js
EXPOSE 3000

# Ejecutar el servidor en modo desarrollo
CMD ["npm", "run", "dev"]
